CREATE OR REPLACE VIEW SalesResume AS
SELECT
	NF.NM_CLIENTE AS NOME_CLIENTE, 
    COUNT(NF.NRO_NOTA) AS TOTAL_NOTAS,
    COUNT(INF.COD_PRODUTO) AS TOTAL_ITENS,
    SUM(INF.QTD_PRODUTO) AS QTD_TOTAL,
    SUM(INF.VL_TOTAL) AS VL_TOTAL,
    MAX(P.VL_PRODUTO) AS MAX_VL_PRODUTO,
    MIN(P.VL_PRODUTO) AS MIN_VL_PRODUTO
FROM
	NOTA_FISCAL AS NF
    INNER JOIN ITEM_NOTA_FISCAL AS INF
		ON NF.NRO_NOTA = INF.NRO_NOTA
	INNER JOIN PRODUTO AS P
		ON INF.COD_PRODUTO = P.COD_PRODUTO
GROUP BY
	NF.NM_CLIENTE