INSERT INTO 
	PEDIDO(ID_UNIDADE, DT_VENDA, VL_TOTAL, TIPO_PAGAMENTO, ID_CLIENTE) VALUES
	(2, NOW(), 0, "Cartão de Crédito", 1);

CALL INSERIR_INGRESSO(1,2,"C",9,TRUE);

CALL ADICIONAR_PRODUTO_A_VENDA(9,5,2);