DELIMITER $$

CREATE PROCEDURE `GET_RELATORIO_RECEITA_FILME`(
	IN P_ID_FILME INT,
    IN P_DATA_INICIO DATE,
    IN P_DATA_FIM DATE
)
BEGIN
	SELECT 
		F.ID_FILME,
        F.TITULO,
        COUNT(VI.ID_INGRESSO) AS QUANTIDADE_INGRESSOS,
        SUM(VI.VALOR) AS RECEITA_TOTAL
	FROM 
		VENDA_INGRESSO VI
	JOIN 
		INGRESSO I ON VI.ID_INGRESSO = I.ID_INGRESSO
	JOIN 
		SESSAO S ON I.ID_SESSAO = S.ID_SESSAO
	JOIN 
		FILME F ON S.ID_FILME = F.ID_FILME
	JOIN 
		PEDIDO P ON VI.ID_VENDA = P.ID_VENDA
	WHERE 
		(P_ID_FILME IS NULL OR F.ID_FILME = P_ID_FILME)
		AND DATE(P.DT_VENDA) BETWEEN P_DATA_INICIO AND P_DATA_FIM
	GROUP BY 
		F.ID_FILME, F.TITULO
	ORDER BY 
		RECEITA_TOTAL DESC;
END$$

DELIMITER ;
