DELIMITER $$

CREATE PROCEDURE `GET_RELATORIO_VENDAS_POR_UNIDADE`(
	IN P_DATA_INICIO DATE,
    IN P_DATA_FIM DATE
)
BEGIN
	SELECT 
		U.ID_UNIDADE,
        U.NOME_FANTASIA,
        COUNT(P.ID_VENDA) AS TOTAL_VENDAS,
        SUM(P.VL_TOTAL) AS RECEITA_TOTAL
	FROM 
		PEDIDO P
	JOIN 
		UNIDADE U ON P.ID_UNIDADE = U.ID_UNIDADE
	WHERE 
		DATE(P.DT_VENDA) BETWEEN P_DATA_INICIO AND P_DATA_FIM
	GROUP BY 
		U.ID_UNIDADE, U.NOME_FANTASIA
	ORDER BY 
		RECEITA_TOTAL DESC;
END$$

DELIMITER ;
