DELIMITER $$

CREATE PROCEDURE `INSERIR_INGRESSO`(
    IN P_ID_SESSAO INT,
    IN P_NUM_POLTRONA INT,
    IN P_FILEIRA CHAR(1),
    IN P_ID_VENDA INT,
    IN P_MEIA_ENTRADA BOOL
)
BEGIN
    DECLARE V_POLTRONA_OCUPADA INT;
    DECLARE V_ID_INGRESSO INT;
    DECLARE V_VALOR_BASE_INGRESSO FLOAT DEFAULT 24.00;
    DECLARE V_VALOR_FINAL_INGRESSO FLOAT;
    DECLARE V_IS_VIP BOOLEAN;

    SELECT VIP
    INTO V_IS_VIP
    FROM SALA_POLTRONA
    WHERE ID_SALA = (SELECT ID_SALA FROM SESSAO WHERE ID_SESSAO = P_ID_SESSAO LIMIT 1)
      AND NUM_POLTRONA = P_NUM_POLTRONA
      AND FILEIRA = P_FILEIRA;

    IF V_IS_VIP THEN
        SET V_VALOR_BASE_INGRESSO = V_VALOR_BASE_INGRESSO + 2.00;
    END IF;

    IF P_MEIA_ENTRADA THEN
        SET V_VALOR_FINAL_INGRESSO = V_VALOR_BASE_INGRESSO / 2;
    ELSE
        SET V_VALOR_FINAL_INGRESSO = V_VALOR_BASE_INGRESSO;
    END IF;

    SELECT COUNT(*)
    INTO V_POLTRONA_OCUPADA
    FROM INGRESSO
    WHERE ID_SESSAO = P_ID_SESSAO
      AND NUM_POLTRONA = P_NUM_POLTRONA
      AND FILEIRA = P_FILEIRA;

    IF V_POLTRONA_OCUPADA > 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Poltrona já ocupada para esta sessão.';
    ELSE
        START TRANSACTION;

        INSERT INTO INGRESSO (ID_SESSAO, NUM_POLTRONA, FILEIRA)
        VALUES (P_ID_SESSAO, P_NUM_POLTRONA, P_FILEIRA);

        SET V_ID_INGRESSO = LAST_INSERT_ID();

        INSERT INTO VENDA_INGRESSO (ID_VENDA, ID_INGRESSO, VALOR, MEIA_ENTRADA)
        VALUES (P_ID_VENDA, V_ID_INGRESSO, V_VALOR_FINAL_INGRESSO, P_MEIA_ENTRADA);

        UPDATE PEDIDO
        SET VL_TOTAL = VL_TOTAL + V_VALOR_FINAL_INGRESSO
        WHERE ID_VENDA = P_ID_VENDA;

        COMMIT;
    END IF;

END$$

DELIMITER ;