DELIMITER $$

CREATE PROCEDURE `ADICIONAR_PRODUTO_A_VENDA`(
    IN P_ID_VENDA INT,
    IN P_ID_PRODUTO INT,
    IN P_QTD_VENDA INT
)
BEGIN
    DECLARE V_VALOR_UNITARIO_PRODUTO FLOAT;
    DECLARE V_SUBTOTAL_PRODUTO FLOAT;
    DECLARE V_PRODUTO_EXISTENTE_NA_VENDA INT;

    START TRANSACTION;

    SELECT VL_PRODUTO
    INTO V_VALOR_UNITARIO_PRODUTO
    FROM PRODUTO
    WHERE ID_PRODUTO = P_ID_PRODUTO;

    SET V_SUBTOTAL_PRODUTO = V_VALOR_UNITARIO_PRODUTO * P_QTD_VENDA;

    SELECT COUNT(*)
    INTO V_PRODUTO_EXISTENTE_NA_VENDA
    FROM VENDA_PRODUTO
    WHERE ID_VENDA = P_ID_VENDA AND ID_PRODUTO = P_ID_PRODUTO;

    IF V_PRODUTO_EXISTENTE_NA_VENDA > 0 THEN
        UPDATE VENDA_PRODUTO
        SET QTD_VENDA = QTD_VENDA + P_QTD_VENDA
        WHERE ID_VENDA = P_ID_VENDA AND ID_PRODUTO = P_ID_PRODUTO;
    ELSE
        INSERT INTO VENDA_PRODUTO (ID_VENDA, ID_PRODUTO, QTD_VENDA)
        VALUES (P_ID_VENDA, P_ID_PRODUTO, P_QTD_VENDA);
    END IF;

    UPDATE PEDIDO
    SET VL_TOTAL = VL_TOTAL + V_SUBTOTAL_PRODUTO
    WHERE ID_VENDA = P_ID_VENDA;

    COMMIT;

END$$

DELIMITER ;