CREATE DATABASE CONSULTA_MEDICA;

USE CONSULTA_MEDICA;

CREATE TABLE CIDADES(
	CEP CHAR(9) PRIMARY KEY NOT NULL,
    UF CHAR(2) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL
);

CREATE TABLE PACIENTE(
	ID_PACIENTE INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    RG CHAR(9) NOT NULL UNIQUE,
    CPF CHAR(13) NOT NULL UNIQUE,
    NOME VARCHAR(80) NOT NULL,
    DT_NASCIMENTO DATE NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    SEXO VARCHAR(20) NOT NULL,
    ESTADO_CIVIL VARCHAR(20) NOT NULL,
    RUA VARCHAR(30) NOT NULL,
    NUM INT,
    CEP CHAR(9) NOT NULL,
    FOREIGN KEY (CEP) REFERENCES CIDADES(CEP)
);

CREATE TABLE MEDICO(
	ID_MEDICO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    RG CHAR(9) NOT NULL UNIQUE,
    CPF CHAR(13) NOT NULL UNIQUE,
    NOME VARCHAR(80) NOT NULL,
    DT_NASCIMENTO DATE NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    SEXO VARCHAR(20) NOT NULL,
    RUA VARCHAR(30) NOT NULL,
    NUM INT,
    CEP CHAR(9) NOT NULL,
    FOREIGN KEY (CEP) REFERENCES CIDADES(CEP)
);

CREATE TABLE CONSULTAS(
	ID_CONSULTA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_PACIENTE INT NOT NULL,
    ID_MEDICO INT NOT NULL,
    DT_CONSULTA DATE NOT NULL,
    DIAGNOSTICO VARCHAR(300) NOT NULL,
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID_PACIENTE),
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO (ID_MEDICO)
);

CREATE TABLE EXAME (
	ID_EXAME INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_CONSULTA INT NOT NULL,
	DT_CONSULTA DATE NOT NULL,
    FOREIGN KEY (ID_CONSULTA) REFERENCES CONSULTAS (ID_CONSULTA)
);