DELIMITER $$

CREATE TRIGGER TRG_DECREMENTA_QTD_VIP
AFTER DELETE ON SALA_POLTRONA
FOR EACH ROW
BEGIN
    IF OLD.VIP = TRUE THEN
        UPDATE SALA_CINEMA
        SET QTD_VIP = CASE
                         WHEN QTD_VIP > 0 THEN QTD_VIP - 1
                         ELSE 0
                      END
        WHERE ID_SALA = OLD.ID_SALA;
    END IF;
END;

$$

DELIMITER ;
