DELIMITER $$

CREATE TRIGGER TRG_DECREMENTA_QTD_POLTRONA
AFTER DELETE ON SALA_POLTRONA
FOR EACH ROW
BEGIN
    UPDATE SALA_CINEMA
    SET QTD_POLTRONA = CASE
                           WHEN QTD_POLTRONA > 0 THEN QTD_POLTRONA - 1
                           ELSE 0
                        END
    WHERE ID_SALA = OLD.ID_SALA;
END

$$

DELIMITER ;