DELIMITER $$

CREATE TRIGGER TRG_DECREMENTA_QTD_VIP
AFTER DELETE ON SALA_POLTRONA
FOR EACH ROW
BEGIN
    DECLARE V_ID_UNIDADE INT;

    SELECT ID_UNIDADE
    INTO V_ID_UNIDADE
    FROM SALA_CINEMA
    WHERE ID_SALA = OLD.ID_SALA
    LIMIT 1;

    IF OLD.VIP = TRUE THEN
        UPDATE SALA_CINEMA
        SET QTD_VIP = CASE
                         WHEN QTD_VIP > 0 THEN QTD_VIP - 1
                         ELSE 0
                      END
        WHERE ID_SALA = OLD.ID_SALA
          AND ID_UNIDADE = V_ID_UNIDADE;
    END IF;
END;

$$

DELIMITER ;