DELIMITER $$

CREATE TRIGGER TGR_DECREMENTA_SALAS_CINEMA
AFTER DELETE ON SALA_CINEMA
FOR EACH ROW
BEGIN
    UPDATE UNIDADE
    SET QTD_SALAS = QTD_SALAS - 1
    WHERE ID_UNIDADE = OLD.ID_UNIDADE;
END;

$$

DELIMITER ;
