DELIMITER $$

CREATE TRIGGER TRG_DECREMENTA_QTD_POLTRONA
AFTER DELETE ON SALA_POLTRONA
FOR EACH ROW
BEGIN
    DECLARE V_ID_UNIDADE INT;

    SELECT ID_UNIDADE
    INTO V_ID_UNIDADE
    FROM SALA_CINEMA
    WHERE ID_SALA = OLD.ID_SALA
    LIMIT 1;

    UPDATE SALA_CINEMA
    SET QTD_POLTRONA = CASE
                           WHEN QTD_POLTRONA > 0 THEN QTD_POLTRONA - 1
                           ELSE 0
                        END
    WHERE ID_SALA = OLD.ID_SALA
      AND ID_UNIDADE = V_ID_UNIDADE;
END

$$

DELIMITER ;