DELIMITER $$

CREATE TRIGGER TGR_DECREMENTA_SALAS_CINEMA
AFTER DELETE ON SALA_CINEMA
FOR EACH ROW
BEGIN
    UPDATE UNIDADE
    SET QTD_SALAS = CASE
                        WHEN QTD_SALAS > 0 THEN QTD_SALAS - 1
                        ELSE 0
                    END
    WHERE ID_UNIDADE = OLD.ID_UNIDADE;
END;

$$

DELIMITER ;