DELIMITER $$

CREATE TRIGGER TRG_INCREMENTA_QTD_POLTRONA
AFTER INSERT ON SALA_POLTRONA
FOR EACH ROW
BEGIN
    DECLARE V_ID_UNIDADE INT;

    SELECT ID_UNIDADE
    INTO V_ID_UNIDADE
    FROM SALA_CINEMA
    WHERE ID_SALA = NEW.ID_SALA
    LIMIT 1;

    UPDATE SALA_CINEMA
    SET QTD_POLTRONA = IFNULL(QTD_POLTRONA, 0) + 1
    WHERE ID_SALA = NEW.ID_SALA
      AND ID_UNIDADE = V_ID_UNIDADE;
END

$$

DELIMITER ;