DELIMITER $$

CREATE TRIGGER TRG_INCREMENTA_QTD_POLTRONA
AFTER INSERT ON SALA_POLTRONA
FOR EACH ROW
BEGIN
    UPDATE SALA_CINEMA
    SET QTD_POLTRONA = IFNULL(QTD_POLTRONA, 0) + 1
    WHERE ID_SALA = NEW.ID_SALA;
END

$$

DELIMITER ;