DELIMITER $$

CREATE TRIGGER TRG_INCREMENTA_QTD_SALAS
AFTER INSERT ON SALA_CINEMA
FOR EACH ROW
BEGIN
    UPDATE UNIDADE
    SET QTD_SALAS = IFNULL(QTD_SALAS, 0) + 1
    WHERE ID_UNIDADE = NEW.ID_UNIDADE;
END;

$$

DELIMITER ;