DELIMITER $$

CREATE TRIGGER TRG_INCREMENTA_QTD_VIP
AFTER INSERT ON SALA_POLTRONA
FOR EACH ROW
BEGIN
    DECLARE V_ID_UNIDADE INT;

    SELECT ID_UNIDADE
    INTO V_ID_UNIDADE
    FROM SALA_CINEMA
    WHERE ID_SALA = NEW.ID_SALA
    LIMIT 1;

    IF NEW.VIP = TRUE THEN
        UPDATE SALA_CINEMA
        SET QTD_VIP = IFNULL(QTD_VIP, 0) + 1
        WHERE ID_SALA = NEW.ID_SALA
          AND ID_UNIDADE = V_ID_UNIDADE;
    END IF;
END;

$$

DELIMITER ;