DELIMITER $$

CREATE TRIGGER TRG_UPDATE_QTD_VIP
AFTER UPDATE ON SALA_POLTRONA
FOR EACH ROW
BEGIN
    DECLARE V_ID_UNIDADE INT;

    SELECT ID_UNIDADE
    INTO V_ID_UNIDADE
    FROM SALA_CINEMA
    WHERE ID_SALA = NEW.ID_SALA
    LIMIT 1;

    IF OLD.VIP = 0 AND NEW.VIP = 1 THEN
        UPDATE SALA_CINEMA
        SET QTD_VIP = IFNULL(QTD_VIP, 0) + 1
        WHERE ID_SALA = NEW.ID_SALA
          AND ID_UNIDADE = V_ID_UNIDADE;
    END IF;

    IF OLD.VIP = 1 AND NEW.VIP = 0 THEN
        UPDATE SALA_CINEMA
        SET QTD_VIP = CASE
                         WHEN QTD_VIP > 0 THEN QTD_VIP - 1
                         ELSE 0
                      END
        WHERE ID_SALA = NEW.ID_SALA
          AND ID_UNIDADE = V_ID_UNIDADE;
    END IF;
END;

$$

DELIMITER ;