DELIMITER $$

CREATE TRIGGER TRG_UPDATE_QTD_POLTRONA
AFTER UPDATE ON SALA_POLTRONA
FOR EACH ROW
BEGIN
    IF OLD.ID_SALA <> NEW.ID_SALA THEN
        UPDATE SALA_CINEMA
        SET QTD_POLTRONA = IFNULL(QTD_POLTRONA, 0) + 1
        WHERE ID_SALA = NEW.ID_SALA;

        UPDATE SALA_CINEMA
        SET QTD_POLTRONA = CASE
                               WHEN QTD_POLTRONA > 0 THEN QTD_POLTRONA - 1
                               ELSE 0
                            END
        WHERE ID_SALA = OLD.ID_SALA;
    END IF;
END

$$

DELIMITER ;