CREATE DATABASE CINEMAS;

USE CINEMAS;

CREATE TABLE PAIS (
    ID_PAIS INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME_PAIS VARCHAR(100) NOT NULL
);

CREATE TABLE PESSOA (
    ID_PESSOA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    SEXO VARCHAR(20) NOT NULL,
    DT_NASCIMENTO DATE NOT NULL,
    ID_PAIS INT NOT NULL,
    FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS)
);

CREATE TABLE ATOR (
    ID_ATOR INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_PESSOA INT NOT NULL,
    FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID_PESSOA)
);

CREATE TABLE DIRETOR (
    ID_DIRETOR INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_PESSOA INT NOT NULL,
    FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID_PESSOA)
);

CREATE TABLE ESTUDIO (
    ID_ESTUDIO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL
);

CREATE TABLE IDIOMA (
    ID_IDIOMA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    IDIOMA VARCHAR(30) NOT NULL
);

CREATE TABLE GENERO (
    ID_GENERO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    GENERO_FILME VARCHAR(100) NOT NULL
);

CREATE TABLE PREMACAO (
    ID_PREMACAO INT PRIMARY KEY,
    NOME_PREMACAO VARCHAR(100)
);

CREATE TABLE FILME (
    ID_FILME INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TITULO VARCHAR(75) NOT NULL,
    ID_DIRETOR INT NOT NULL,
    DURACAO INT NOT NULL,
    CLASSIFICACAO_IDADE INT NOT NULL,
    NOTA FLOAT,
    DESCRICAO TEXT,
    SINOPSE VARCHAR(100),
    DT_LANCAMENTO DATE NOT NULL,
    ID_IDIOMA INT NOT NULL,
    RECEITA FLOAT, -- valor gasto na produção do filme
    ID_ESTUDIO INT NOT NULL,
    FOREIGN KEY (ID_DIRETOR) REFERENCES DIRETOR(ID_DIRETOR),
    FOREIGN KEY (ID_IDIOMA) REFERENCES IDIOMA(ID_IDIOMA),
    FOREIGN KEY (ID_ESTUDIO) REFERENCES ESTUDIO(ID_ESTUDIO)
);

CREATE TABLE GENERO_FILME (
    ID_GENERO INT NOT NULL,
    ID_FILME INT NOT NULL,
    PRIMARY KEY (ID_GENERO, ID_FILME),
    FOREIGN KEY (ID_GENERO) REFERENCES GENERO(ID_GENERO),
    FOREIGN KEY (ID_FILME) REFERENCES FILME(ID_FILME)
);

CREATE TABLE PREMACAO_FILME (
    ID_PREMACAO INT NOT NULL,
    ID_FILME INT NOT NULL,
    DT_PREMACAO DATE NOT NULL,
    PRIMARY KEY (ID_PREMACAO, ID_FILME),
    FOREIGN KEY (ID_PREMACAO) REFERENCES PREMACAO(ID_PREMACAO),
    FOREIGN KEY (ID_FILME) REFERENCES FILME(ID_FILME)
);

CREATE TABLE PREMACAO_ATOR (
    ID_PREMACAO INT NOT NULL,
    ID_FILME INT NOT NULL,
    ID_ATOR INT NOT NULL,
    DT_PREMACAO DATE NOT NULL,
    PRIMARY KEY (ID_PREMACAO, ID_FILME, ID_ATOR),
    FOREIGN KEY (ID_PREMACAO) REFERENCES PREMACAO(ID_PREMACAO),
    FOREIGN KEY (ID_FILME) REFERENCES FILME(ID_FILME),
    FOREIGN KEY (ID_ATOR) REFERENCES ATOR(ID_ATOR)
);

CREATE TABLE ATOR_FILME (
    ID_ATOR INT NOT NULL,
    ID_FILME INT NOT NULL,
    PRIMARY KEY (ID_ATOR, ID_FILME),
    FOREIGN KEY (ID_ATOR) REFERENCES ATOR(ID_ATOR),
    FOREIGN KEY (ID_FILME) REFERENCES FILME(ID_FILME)
);

CREATE TABLE CIDADE (
    CEP CHAR(9) PRIMARY KEY NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    UF CHAR(2) NOT NULL
);

CREATE TABLE FRANQUIA (
    ID_FRANQUIA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME_FRANQUIA VARCHAR(100) NOT NULL,
    E_MAIL VARCHAR(75)
);

CREATE TABLE UNIDADE (
    ID_UNIDADE INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME_FANTASIA VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(20),
    E_MAIL VARCHAR(75) NOT NULL,
    QTD_SALAS INT,
    CEP CHAR(9) NOT NULL,
    RUA VARCHAR(40) NOT NULL,
    NUM VARCHAR(5),
    ID_FRANQUIA INT NOT NULL,
    FOREIGN KEY (CEP) REFERENCES CIDADE(CEP),
    FOREIGN KEY (ID_FRANQUIA) REFERENCES FRANQUIA(ID_FRANQUIA)
);

CREATE TABLE SALA_CINEMA (
    ID_SALA INT NOT NULL AUTO_INCREMENT,
    ID_UNIDADE INT NOT NULL,
    QTD_POLTRONA INT,
    QTD_VIP INT,
    PRIMARY KEY(ID_SALA, ID_UNIDADE),
    FOREIGN KEY (ID_UNIDADE) REFERENCES UNIDADE(ID_UNIDADE)
);

CREATE TABLE SALA_POLTRONA (
    ID_SALA INT NOT NULL,
    FILEIRA CHAR(1) NOT NULL,
    NUM_POLTRONA INT NOT NULL,
    VIP BOOL,
    PRIMARY KEY (ID_SALA, FILEIRA, NUM_POLTRONA),
    FOREIGN KEY (ID_SALA) REFERENCES SALA_CINEMA(ID_SALA)
);


CREATE TABLE LEGENDA (
    ID_LEGENDA INT AUTO_INCREMENT,
    ID_IDIOMA INT NOT NULL,
    PRIMARY KEY (ID_LEGENDA, ID_IDIOMA),
    FOREIGN KEY (ID_IDIOMA) REFERENCES IDIOMA(ID_IDIOMA)
);

CREATE TABLE SESSAO (
    ID_SESSAO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_FILME INT NOT NULL,
    HR_SESSAO DATETIME NOT NULL,
    ID_IDIOMA INT NOT NULL,
    ID_SALA INT NOT NULL,
    ID_LEGENDA INT,
    FOREIGN KEY (ID_FILME) REFERENCES FILME(ID_FILME),
    FOREIGN KEY (ID_IDIOMA) REFERENCES IDIOMA(ID_IDIOMA),
    FOREIGN KEY (ID_SALA) REFERENCES SALA_CINEMA(ID_SALA),
    FOREIGN KEY (ID_LEGENDA) REFERENCES LEGENDA(ID_LEGENDA)
);


CREATE TABLE INGRESSO (
    ID_INGRESSO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_SESSAO INT NOT NULL,
    NUM_POLTRONA INT NOT NULL,
    FILEIRA CHAR(1) NOT NULL,
    FOREIGN KEY (ID_SESSAO) REFERENCES SESSAO(ID_SESSAO)
);

CREATE TABLE FUNCAO (
    ID_FUNCAO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CARGO VARCHAR(30) NOT NULL
);

CREATE TABLE FUNCIONARIO (
    ID_FUNCIONARIO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CPF CHAR(14) NOT NULL UNIQUE,
    NOME VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(20),
    E_MAIL VARCHAR(75) NOT NULL,
    ID_UNIDADE INT NOT NULL,
    ID_FUNCAO INT NOT NULL,
    DT_CONTRATACAO DATE NOT NULL,
    FOREIGN KEY (ID_UNIDADE) REFERENCES UNIDADE(ID_UNIDADE),
    FOREIGN KEY (ID_FUNCAO) REFERENCES FUNCAO(ID_FUNCAO)
);

CREATE TABLE CLIENTE (
    ID_CLIENTE INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CPF CHAR(14) UNIQUE,
    NOME VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(20),
    DT_CADASTRO DATETIME NOT NULL
);

CREATE TABLE PRODUTO (
    ID_PRODUTO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME_PRODUTO VARCHAR(50) NOT NULL,
    VL_PRODUTO FLOAT NOT NULL,
    DESC_PRODUTO VARCHAR(200),
    UN_MEDIDA CHAR(2) NOT NULL
);

CREATE TABLE PEDIDO (
    ID_VENDA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_UNIDADE INT NOT NULL,
    DT_VENDA DATETIME NOT NULL,
    VL_TOTAL FLOAT NOT NULL,
    TIPO_PAGAMENTO VARCHAR(20) NOT NULL,
    ID_CLIENTE INT NOT NULL,
    FOREIGN KEY (ID_UNIDADE) REFERENCES UNIDADE(ID_UNIDADE),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE VENDA_PRODUTO (
    ID_VENDA INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QTD_VENDA INT NOT NULL,
    PRIMARY KEY (ID_VENDA, ID_PRODUTO),
    FOREIGN KEY (ID_VENDA) REFERENCES PEDIDO(ID_VENDA),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);

CREATE TABLE VENDA_INGRESSO (
    ID_VENDA INT NOT NULL,
    ID_INGRESSO INT NOT NULL,
    VALOR FLOAT NOT NULL,
    MEIA_ENTRADA BOOL,
    PRIMARY KEY (ID_VENDA, ID_INGRESSO),
    FOREIGN KEY (ID_VENDA) REFERENCES PEDIDO(ID_VENDA),
    FOREIGN KEY (ID_INGRESSO) REFERENCES INGRESSO(ID_INGRESSO)
);