CREATE OR REPLACE VIEW VIEW_INGRESSO_COMPLETO AS
SELECT
	F.TITULO AS FILME,
    
    CASE 
		WHEN S.ID_IDIOMA = F.ID_IDIOMA THEN 'ÁUDIO ORIGINAL'
        ELSE 'DUBLADO'
	END AS AUDIO,
    
    COALESCE(IDM_LEGENDA.IDIOMA, 'NÃO TEM') AS LEGENDA,
    
    CONCAT(I.FILEIRA, I.NUM_POLTRONA) AS POLTRONA,
    
    CASE 
		WHEN SP.VIP = TRUE THEN 'PREMIUM'
        ELSE 'NORMAL'
	END AS SETOR,
    
    U.NOME_FANTASIA AS UNIDADE,
    
    CONCAT(U.RUA, ', ', U.NUM, ', ', C.CIDADE, ' - ', C.UF) AS ENDERECO,
    
    VI.VALOR AS VALOR_INGRESSO,
    
    CASE 
		WHEN VI.MEIA_ENTRADA = TRUE THEN 'SIM'
        ELSE 'NÃO'
	END AS MEIA_ENTRADA

FROM 
	VENDA_INGRESSO AS VI
    INNER JOIN INGRESSO AS I
		ON VI.ID_INGRESSO = I.ID_INGRESSO
	INNER JOIN SESSAO AS S
		ON I.ID_SESSAO = S.ID_SESSAO
	INNER JOIN FILME AS F
		ON S.ID_FILME = F.ID_FILME
	INNER JOIN SALA_CINEMA AS SC
		ON S.ID_SALA = SC.ID_SALA
	INNER JOIN SALA_POLTRONA AS SP
		ON I.FILEIRA = SP.FILEIRA 
		AND I.NUM_POLTRONA = SP.NUM_POLTRONA 
		AND SP.ID_SALA = SC.ID_SALA
	INNER JOIN PEDIDO AS P
		ON VI.ID_VENDA = P.ID_VENDA
	INNER JOIN UNIDADE AS U
		ON P.ID_UNIDADE = U.ID_UNIDADE
	INNER JOIN CIDADE AS C
		ON U.CEP = C.CEP
	LEFT JOIN LEGENDA AS LG
		ON LG.ID_SESSAO = S.ID_SESSAO
	LEFT JOIN IDIOMA AS IDM_LEGENDA
		ON LG.ID_IDIOMA = IDM_LEGENDA.ID_IDIOMA;
