CREATE OR REPLACE VIEW INGRESSO_COMPLETO AS
SELECT
    F.TITULO AS NOME_FILME,
    I_SESSAO.IDIOMA AS IDIOMA_SESSAO,
    CASE
        WHEN S.ID_LEGENDA IS NOT NULL THEN I_LEGENDA.IDIOMA
        ELSE 'Não Contém'
    END AS IDIOMA_LEGENDA,
    CONCAT(I.FILEIRA, I.NUM_POLTRONA) AS POLTRONA,
    CASE
        WHEN SP.VIP = 1 THEN 'PREMIUM'
        ELSE 'NORMAL'
    END AS SETOR,
    CASE
        WHEN S.3D = TRUE THEN 'SIM'
        ELSE 'NÃO'
    END AS EH_3D, -- Novo campo para indicar se a sessão é 3D
    U.NOME_FANTASIA AS NOME_UNIDADE,
    CONCAT(U.RUA, ', ', U.NUM, ' - ', C.CIDADE, '/', C.UF, ' - CEP: ', C.CEP) AS ENDERECO_UNIDADE,
    VI.VALOR AS VALOR_INGRESSO,
    CASE
        WHEN VI.MEIA_ENTRADA = 1 THEN 'SIM'
        ELSE 'NÃO'
    END AS MEIA_ENTRADA
FROM
    INGRESSO AS I
    INNER JOIN SESSAO AS S
        ON I.ID_SESSAO = S.ID_SESSAO
    INNER JOIN FILME AS F
        ON S.ID_FILME = F.ID_FILME
    INNER JOIN IDIOMA AS I_SESSAO
        ON S.ID_IDIOMA = I_SESSAO.ID_IDIOMA
    LEFT JOIN LEGENDA AS L
        ON S.ID_LEGENDA = L.ID_LEGENDA
    LEFT JOIN IDIOMA AS I_LEGENDA
        ON L.ID_IDIOMA = I_LEGENDA.ID_IDIOMA
    INNER JOIN SALA_CINEMA AS SC
        ON S.ID_SALA = SC.ID_SALA
    INNER JOIN SALA_POLTRONA AS SP
        ON S.ID_SALA = SP.ID_SALA
        AND I.FILEIRA = SP.FILEIRA
        AND I.NUM_POLTRONA = SP.NUM_POLTRONA
    INNER JOIN UNIDADE AS U
        ON SC.ID_UNIDADE = U.ID_UNIDADE
    INNER JOIN CIDADE AS C
        ON U.CEP = C.CEP
    INNER JOIN VENDA_INGRESSO AS VI
        ON I.ID_INGRESSO = VI.ID_INGRESSO
    INNER JOIN PEDIDO AS P
        ON VI.ID_VENDA = P.ID_VENDA;